version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: pg-local
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pokeapi
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pokeapi"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  pg_data:
